version: '3.8'

services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "3000:3000"
    depends_on:
      - counter-service

  counter-service:
    build:
      context: .
      dockerfile: Dockerfile.counter
    volumes:
      - "./counters:/app/counters"
